'use strict';
const express = require('express');
import Customer from '../controller/fabricationVirtualData/customer/customer.js';
import Feedback from '../controller/fabricationVirtualData/feedback/feedback.js';
import Blacklist from '../controller/fabricationVirtualData/blacklist/blacklist.js';
import Attachment from '../controller/fabricationVirtualData/attachment/attachment.js';
import Audit from '../controller/fabricationVirtualData/audit/audit.js';
import Inform from '../controller/fabricationVirtualData/inform/inform.js';
import Dynamic from '../controller/fabricationVirtualData/dynamic/dynamic.js';
import Topic from '../controller/fabricationVirtualData/topic/topic.js';
import Recommend from '../controller/fabricationVirtualData/recommend/recommend.js';
import Article from '../controller/fabricationVirtualData/article/article.js';
import Template from '../controller/fabricationVirtualData/template/template.js';
import Message from '../controller/fabricationVirtualData/message/message';
import Scene from '../controller/fabricationVirtualData/scene/scene.js';
const router = express.Router();
router.get('/customer',Customer.createCustomer);
router.get('/feedBack',Feedback.createFeedback);
router.get('/blacklist',Blacklist.createBlackCustomer);
router.get('/attachment',Attachment.createBlackCustomer);
router.get('/audit',Audit.createBlackCustomer);
router.get('/inform',Inform.createInform);
router.get('/dynamic',Dynamic.createBlackCustomer);
router.get('/topic',Topic.createCustomer);
router.get('/recommend',Recommend.createInform);
router.get('/article',Article.createCustomer);
router.get('/template',Template.createCustomer);
router.get('/message',Message.createCustomer);
router.get('/scene',Scene.createCustomer);
export default router;
