'use strict';
const express = require('express');
import Customer from '../controller/fabricationVirtualData/customer/customer.js';
import Feedback from '../controller/fabricationVirtualData/feedback/feedback.js';
import Blacklist from '../controller/fabricationVirtualData/blacklist/blacklist.js';
import Attachment from '../controller/fabricationVirtualData/attachment/attachment.js';
import Audit from '../controller/fabricationVirtualData/audit/audit.js';
import Inform from '../controller/fabricationVirtualData/inform/inform.js';
const router = express.Router();
router.get('/customer',Customer.createCustomer);
router.get('/feedBack',Feedback.createFeedback);
router.get('/blacklist',Blacklist.createBlackCustomer);
router.get('/attachment',Attachment.createBlackCustomer);
router.get('/audit',Audit.createBlackCustomer);
router.get('/inform',Inform.createInform);
export default router;