'use strict';
const express = require('express');
import Customer from '../controller/customer/customer.js';
const router = express.Router();
router.get('/getCustomerList',Customer.getJsonList);
router.get('/getAuditList',Customer.getJsonList);
router.post('/getAuditAttachmentList',Customer.getAttachmentList);
router.get('/getFeedBackList',Customer.getJsonList);
router.get('/getInformList',Customer.getJsonList);
router.post('/blackening',Customer.changeCustomerState);
router.post('/report',Customer.reportCustomer);
router.post('/replyToReport',Customer.replyToReport);
router.post('/activate',Customer.changeCustomerState);
router.post('/rejectAudit',Customer.changeCustomerState);
router.get('/getBlacklist',Customer.getJsonList);
router.get('/getAttachmentList',Customer.getJsonList);
export default router;